# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Therapist', to=settings.AUTH_USER_MODEL),
        ),
    ]
