# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_auto_20170506_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='patient',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Therapist')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewapp.Therapist'),
        ),
    ]
