# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_auto_20170508_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
